server:
  port: 8080
  address: localhost
#热部署
spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://x.x.x.x:3306/blog
    username: xx
    password: xx
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  #更新数据库
    show-sql: true   #是否显示sql语句

#  h2:
#    console:
#      enabled: true


# 配置ElasticSearch

  data:
    elasticsearch:
      cluster-nodes: x.x.x.x:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true

